// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjektNYYYZealand.Models
{
    [Table("BogHold")]
    public partial class BogHold
    {
        [Key]
        [Column("BogHold_Id")]
        public int BogHoldId { get; set; }
        [Column("Bog_Id")]
        public int BogId { get; set; }
        [Column("Hold_Id")]
        public int HoldId { get; set; }

        [ForeignKey(nameof(BogId))]
        [InverseProperty("BogHolds")]
        public virtual Bog Bog { get; set; }
        [ForeignKey(nameof(HoldId))]
        [InverseProperty("BogHolds")]
        public virtual Hold Hold { get; set; }
    }
}