// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjektNYYYZealand.Models
{
    [Table("Underviser")]
    public partial class Underviser
    {
        public Underviser()
        {
            UndervisereHolds = new HashSet<UndervisereHold>();
        }

        [Key]
        [Column("Underviser_id")]
        public int UnderviserId { get; set; }
        public int MedarbejderNumber { get; set; }
        [Required]
        [StringLength(256)]
        public string Name { get; set; }
        [Required]
        [StringLength(256)]
        public string Email { get; set; }

        [InverseProperty(nameof(UndervisereHold.Underviser))]
        public virtual ICollection<UndervisereHold> UndervisereHolds { get; set; }
    }
}