// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjektNYYYZealand.Models
{
    [Table("UndervisereHold")]
    public partial class UndervisereHold
    {
        [Key]
        [Column("UndervisereHold_Id")]
        public int UndervisereHoldId { get; set; }
        [Column("Hold_Id")]
        public int HoldId { get; set; }
        [Column("Underviser_Id")]
        public int UnderviserId { get; set; }

        [ForeignKey(nameof(HoldId))]
        [InverseProperty("UndervisereHolds")]
        public virtual Hold Hold { get; set; }
        [ForeignKey(nameof(UnderviserId))]
        [InverseProperty("UndervisereHolds")]
        public virtual Underviser Underviser { get; set; }
    }
}